_compreffor.pyx: use list instead of array.array to support pypy
Apparently using cpython's array.array is not supported on pypy.
It gives me this error:

File "array.pxd", line 58, in init compreffor._compreffor
ValueError: array.array has the wrong size, try recompiling. Expected 24, got 64

If I return a simple list of integers, it works.